### ISSUE TITLE
New OWL gen scripts using SCOWL

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#34]
- [x] setup scala environment + project using [scowl](https://github.com/phenoscape/scowl) (use sbt for this) @Robbie1977 
- [x] Decide on how neo4j connection will work + JSON handling and write code to support. @Robbie1977 
- [x] Rewrite [definition generation function](https://github.com/phenoscape/scowl) : using SCOWL.  (OWL queries for typing may require some direct calls to OWL-API)
- [x]  rewrite [voxel overlap->overlap function](https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/code/owl_gen/fc_ind.py#L73) to work from channel -channel voxel overlap stored in Cypher.
- [x] Gen by dataset (as now)
- [x] Spec Cypher to OWL expressed as SCOWL manchester @dosumis

**Comment by Robbie1977** [comment]
docker run -it --rm hseeberger/scala-sbt get us a working sbt / scala system

**Comment by dosumis** [comment]
Cool.  Need configs for scowl.

https://github.com/phenoscape/scowl#usage

Have also been looking at sbt-eclipse 

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")

(see http://alvinalexander.com/scala/sbt-how-to-configure-work-with-eclipse-projects)

Could you look into setting up a repo with this + standard file structure?

**Comment by Robbie1977** [comment]
in progress...
